/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package formStaff;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.HashMap;
import javax.swing.table.DefaultTableModel;
import koneksi.koneksi;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author HP
 */
public class FormStaffCetakStruk extends javax.swing.JPanel {

    Connection conn;
    ResultSet rs = null;
    PreparedStatement pst = null;

    /**
     * Creates new form FormAdminDetailStok
     */
    public FormStaffCetakStruk() {
        initComponents();
        table.fixTable(jScrollPane1);
        DefaultTableModel mode = (DefaultTableModel) table.getModel();
        table();
        idTransaksi();
        restok();
    }

    public void restok() {
        ListMenu();
        GetMenu();
    }

    public void ListMenu() {
        String sql = "SELECT id_menu,nama_menu FROM stok_menu";
        try {
            pst = conn.prepareStatement(sql);
            rs = pst.executeQuery();
            makan.removeAllItems();
            while (rs.next()) {
                makan.addItem(rs.getString(2));
            }
        } catch (SQLException ex) {
        }
    }

    public void GetMenu() {
        String sql = "SELECT nama_produk,COUNT(jumlah_beli) FROM detail_transaksi WHERE nama_produk = '" + makan.getSelectedItem() + "'";
        try {
            pst = conn.prepareStatement(sql);
            rs = pst.executeQuery();
            while (rs.next()) {
                jumlah_restok.setText(rs.getString(2));
            }
        } catch (SQLException ex) {
        }
    }

    public void idTransaksi() {
        try {
            conn = DriverManager.getConnection("jdbc:mysql://localhost/mbaknis", "root", "");
            String sql = "select id_detail_transaksi from detail_transaksi order by id_detail_transaksi desc limit 1";
            pst = conn.prepareStatement(sql);
            rs = pst.executeQuery();
            while (rs.next()) {
                txt_cetak.setText(rs.getString(1));
            }
        } catch (Exception e) {
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn_detail1 = new swing.Button();
        btn_detail = new swing.Button();
        button1 = new swing.Button();
        txt_cetak = new javax.swing.JTextField();
        makan = new javax.swing.JComboBox<>();
        jumlah_restok = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        table = new customtable.CustomTable();
        jLabel1 = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(1050, 520));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_detail1.setBackground(new java.awt.Color(73, 255, 90));
        btn_detail1.setForeground(new java.awt.Color(255, 255, 255));
        btn_detail1.setText("Cetak");
        btn_detail1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_detail1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_detail1ActionPerformed(evt);
            }
        });
        add(btn_detail1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 240, 360, 40));

        btn_detail.setBackground(new java.awt.Color(102, 102, 255));
        btn_detail.setForeground(new java.awt.Color(255, 255, 255));
        btn_detail.setText("Kembali");
        btn_detail.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        btn_detail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_detailActionPerformed(evt);
            }
        });
        add(btn_detail, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 410, 160, 30));

        button1.setBackground(new java.awt.Color(73, 255, 90));
        button1.setText("Refresh");
        button1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button1ActionPerformed(evt);
            }
        });
        add(button1, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 410, 120, 30));

        txt_cetak.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        add(txt_cetak, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 140, 250, 30));

        makan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        makan.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
                makanPopupMenuWillBecomeInvisible(evt);
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
            }
        });
        add(makan, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 300, 210, -1));
        add(jumlah_restok, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 300, 50, -1));

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(table);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 100, 550, 290));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imageForm/StaffCetakStruk.png"))); // NOI18N
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1050, 520));
    }// </editor-fold>//GEN-END:initComponents

    private void btn_detailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_detailActionPerformed
        this.setVisible(false);
        txt_cetak.setText("");

    }//GEN-LAST:event_btn_detailActionPerformed

    private void btn_detail1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_detail1ActionPerformed
        // TODO add your handling code here:
        java.sql.Connection con = null;
        try {
            String jdbcDriver = "com.mysql.jdbc.Driver";
            Class.forName(jdbcDriver);

            String url = "jdbc:mysql://localhost:3306/mbaknis";
            String user = "root";
            String pass = "";

            con = DriverManager.getConnection(url, user, pass);
            Statement stm = con.createStatement();

            try {
                String report = ("C:\\Users\\HP\\Documents\\NetBeansProjects\\MbakNis\\src\\formStaff\\newReport.jrxml");
                HashMap hash = new HashMap();
                hash.put("kode", txt_cetak.getText());
                JasperReport JRpt = JasperCompileManager.compileReport(report);
                JasperPrint JPrint = JasperFillManager.fillReport(JRpt, hash, con);
                JasperViewer.viewReport(JPrint, false);
            } catch (Exception e) {
                System.out.println("Gagal Untuk Di Report");
            }

        } catch (Exception e) {
        }
    }//GEN-LAST:event_btn_detail1ActionPerformed

    private void button1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button1ActionPerformed
        // TODO add your handling code here:
        table();
        idTransaksi();
    }//GEN-LAST:event_button1ActionPerformed

    private void makanPopupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_makanPopupMenuWillBecomeInvisible
        // TODO add your handling code here:
        GetMenu();
    }//GEN-LAST:event_makanPopupMenuWillBecomeInvisible

    private void tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableMouseClicked
        // TODO add your handling code here:
        int baris = table.getSelectedRow();
        if (baris != 1);
        {
            String no = table.getValueAt(baris, 0).toString();
            txt_cetak.setText(no);
        }
    }//GEN-LAST:event_tableMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private swing.Button btn_detail;
    private swing.Button btn_detail1;
    private swing.Button button1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jumlah_restok;
    private javax.swing.JComboBox<String> makan;
    private customtable.CustomTable table;
    private javax.swing.JTextField txt_cetak;
    // End of variables declaration//GEN-END:variables

    public void table() {
        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("ID Detail Transaksi");
        model.addColumn("ID Transaksi");
        model.addColumn("Nama Pelanggan");
        model.addColumn("Tanggal Keluar");
        model.addColumn("Pembayaran");
        model.addColumn("Jumlah beli");
        model.addColumn("Nama Produk");

        try {
            String sql = "SELECT detail_transaksi.`id_detail_transaksi`, transaksi.`id_kr`,transaksi.`nama_pelanggan`,transaksi.`tanggal_keluar`,transaksi.`pembayaran`,detail_transaksi.`jumlah_beli`,detail_transaksi.`nama_produk`\n"
                    + "FROM transaksi\n"
                    + "JOIN detail_transaksi\n"
                    + "ON transaksi.`id_kr` = detail_transaksi.`id_kr`";
            java.sql.Connection konek = (Connection) koneksi.configDB();
            pst = konek.prepareStatement(sql);
            rs = pst.executeQuery(sql);
            while (rs.next()) {
                model.addRow(new Object[]{rs.getString(1),
                    rs.getString(2), rs.getString(3), rs.getString(4), rs.getString(5), rs.getString(6), rs.getString(7)
                });
                table.setModel(model);
            }
        } catch (SQLException e) {
        }
    }
}
